package click.opentofu.sprout.handler.tofu.resource.implementations;

import org.springframework.stereotype.Component;

import click.opentofu.sprout.handler.tofu.resource.interfaces.ResourceHandler;

@Component("tofu_resource_instance")
public class TofuResourceInstance implements ResourceHandler {
    @Override
    public String buildTofuResourceMainFile(String region, String account) {
        StringBuilder definedMainFile = new StringBuilder();
        definedMainFile
            .append("variable aws_instance { type = map(map(any)) }\n\n")
            .append("resource aws_instance product {\n")
            .append("    for_each = var.aws_instance\n\n")

            /** Start of Reusable Terraform Module Code Substitution */

            .append("    ami                         = length(trim(lookup(each.value, \"ami\", \"\"), \" \")) > 0 ? lookup(each.value, \"ami\", \"\") : null\n")
            .append("    instance_type               = length(trim(lookup(each.value, \"instance_type\", \"\"), \" \")) > 0 ? lookup(each.value, \"instance_type\", \"\") : null\n")
            .append("    availability_zone           = length(trim(lookup(each.value, \"availability_zone\", \"\"), \" \")) > 0 ? lookup(each.value, \"availability_zone\", \"\") : null\n")
            .append("    subnet_id                   = length(trim(lookup(each.value, \"subnet_id\", \"\"), \" \")) > 0 ? lookup(each.value, \"subnet_id\", \"\") : null\n")
            .append("    private_ip                  = length(trim(lookup(each.value, \"private_ip\", \"\"), \" \")) > 0 ? lookup(each.value, \"private_ip\", \"\") : null\n")
            .append("    key_name                    = length(trim(lookup(each.value, \"key_name\", \"\"), \" \")) > 0 ? lookup(each.value, \"key_name\", \"\") : null\n")
            .append("    iam_instance_profile        = length(trim(lookup(each.value, \"iam_instance_profile\", \"\"), \" \")) > 0 ? lookup(each.value, \"iam_instance_profile\", \"\") : null\n")
            .append("    tenancy                     = length(trim(lookup(each.value, \"tenancy\", \"\"), \" \")) > 0 ? lookup(each.value, \"tenancy\", \"\") : null\n")
            .append("    host_id                     = length(trim(lookup(each.value, \"host_id\", \"\"), \" \")) > 0 ? lookup(each.value, \"host_id\", \"\") : null\n")
            .append("    placement_group             = length(trim(lookup(each.value, \"placement_group\", \"\"), \" \")) > 0 ? lookup(each.value, \"placement_group\", \"\") : null\n")
            .append("    placement_group_id          = length(trim(lookup(each.value, \"placement_group_id\", \"\"), \" \")) > 0 ? lookup(each.value, \"placement_group_id\", \"\") : null\n")
            .append("    host_resource_group_arn     = length(trim(lookup(each.value, \"host_resource_group_arn\", \"\"), \" \")) > 0 ? lookup(each.value, \"host_resource_group_arn\", \"\") : null\n")
            .append("    ipv6_address_count          = length(trim(lookup(each.value, \"ipv6_address_count\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"ipv6_address_count\", \"\")), null) : null\n")
            .append("    placement_partition_number  = length(trim(lookup(each.value, \"placement_partition_number\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"placement_partition_number\", \"\")), null) : null\n")
            .append("    associate_public_ip_address = length(trim(lookup(each.value, \"associate_public_ip_address\", \"\"), \" \")) > 0 ? lookup(each.value, \"associate_public_ip_address\", \"\") == \"true\" ? true : false : null\n")
            .append("    disable_api_stop            = length(trim(lookup(each.value, \"disable_api_stop\", \"\"), \" \")) > 0 ? lookup(each.value, \"disable_api_stop\", \"\") == \"true\" ? true : false : null\n")
            .append("    disable_api_termination     = length(trim(lookup(each.value, \"disable_api_termination\", \"\"), \" \")) > 0 ? lookup(each.value, \"disable_api_termination\", \"\") == \"true\" ? true : false : null\n")
            .append("    ebs_optimized               = length(trim(lookup(each.value, \"ebs_optimized\", \"\"), \" \")) > 0 ? lookup(each.value, \"ebs_optimized\", \"\") == \"true\" ? true : false : null\n")
            .append("    force_destroy               = length(trim(lookup(each.value, \"force_destroy\", \"\"), \" \")) > 0 ? lookup(each.value, \"force_destroy\", \"\") == \"true\" ? true : false : null\n")
            .append("    get_password_data           = length(trim(lookup(each.value, \"get_password_data\", \"\"), \" \")) > 0 ? lookup(each.value, \"get_password_data\", \"\") == \"true\" ? true : false : null\n")
            .append("    hibernation                 = length(trim(lookup(each.value, \"hibernation\", \"\"), \" \")) > 0 ? lookup(each.value, \"hibernation\", \"\") == \"true\" ? true : false : null\n")
            .append("    monitoring                  = length(trim(lookup(each.value, \"monitoring\", \"\"), \" \")) > 0 ? lookup(each.value, \"monitoring\", \"\") == \"true\" ? true : false : null\n")
            .append("    source_dest_check           = length(trim(lookup(each.value, \"source_dest_check\", \"\"), \" \")) > 0 ? lookup(each.value, \"source_dest_check\", \"\") == \"true\" ? true : false : null\n")
            .append("    user_data_replace_on_change = length(trim(lookup(each.value, \"user_data_replace_on_change\", \"\"), \" \")) > 0 ? lookup(each.value, \"user_data_replace_on_change\", \"\") == \"true\" ? true : false : null\n")
            .append("    enable_primary_ipv6         = length(trim(lookup(each.value, \"enable_primary_ipv6\", \"\"), \" \")) > 0 ? lookup(each.value, \"enable_primary_ipv6\", \"\") == \"true\" ? true : false : null\n")
            .append("    ipv6_addresses              = length(trim(lookup(each.value, \"ipv6_addresses\", \"\"), \" \")) > 0 ? compact(split(\"{{__,__}}\", lookup(each.value, \"ipv6_addresses\", \"\"))) : null\n")
            .append("    secondary_private_ips       = length(trim(lookup(each.value, \"secondary_private_ips\", \"\"), \" \")) > 0 ? compact(split(\"{{__,__}}\", lookup(each.value, \"secondary_private_ips\", \"\"))) : null\n")
            .append("    vpc_security_group_ids      = length(trim(lookup(each.value, \"vpc_security_group_ids\", \"\"), \" \")) > 0 ? compact(split(\"{{__,__}}\", lookup(each.value, \"vpc_security_group_ids\", \"\"))) : null\n")
            .append("    security_groups             = length(trim(lookup(each.value, \"security_groups\", \"\"), \" \")) > 0 ? compact(split(\"{{__,__}}\", lookup(each.value, \"security_groups\", \"\"))) : null\n")
            .append("    user_data                   = length(trim(lookup(each.value, \"user_data\", \"\"), \" \")) > 0 ? file(lookup(each.value, \"user_data\", \"\")) : null\n")
            .append("    dynamic \"instance_market_options\" {\n")
            .append("        for_each = length(compact([\n")
            .append("            lookup(each.value, \"market_type\", null),\n")
            .append("            lookup(each.value, \"instance_interruption_behavior\", null),\n")
            .append("            lookup(each.value, \"max_price\", null),\n")
            .append("            lookup(each.value, \"spot_instance_type\", null),\n")
            .append("            lookup(each.value, \"valid_until\", null)\n")
            .append("        ])) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            market_type = length(trim(lookup(each.value, \"market_type\", \"\"), \" \")) > 0 ? lookup(each.value, \"market_type\", \"\") : null\n")
            .append("            spot_options {\n")
            .append("                instance_interruption_behavior = length(trim(lookup(each.value, \"instance_interruption_behavior\", \"\"), \" \")) > 0 ? lookup(each.value, \"instance_interruption_behavior\", \"\") : null\n")
            .append("                max_price                      = length(trim(lookup(each.value, \"max_price\", \"\"), \" \")) > 0 ? lookup(each.value, \"max_price\", \"\") : null\n")
            .append("                spot_instance_type             = length(trim(lookup(each.value, \"spot_instance_type\", \"\"), \" \")) > 0 ? lookup(each.value, \"spot_instance_type\", \"\") : null\n")
            .append("                valid_until                    = length(trim(lookup(each.value, \"valid_until\", \"\"), \" \")) > 0 ? lookup(each.value, \"valid_until\", \"\") : null\n")
            .append("            }\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"launch_template\" {\n")
            .append("        for_each = length(compact([\n")
            .append("            lookup(each.value, \"lt_id\", null),\n")
            .append("            lookup(each.value, \"lt_name\", null),\n")
            .append("            lookup(each.value, \"lt_version\", null)\n")
            .append("        ])) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            id      = length(trim(lookup(each.value, \"lt_id\", \"\"), \" \")) > 0 ? lookup(each.value, \"lt_id\", \"\") : null\n")
            .append("            name    = length(trim(lookup(each.value, \"lt_name\", \"\"), \" \")) > 0 ? lookup(each.value, \"lt_name\", \"\") : null\n")
            .append("            version = length(trim(lookup(each.value, \"lt_version\", \"\"), \" \")) > 0 ? lookup(each.value, \"lt_version\", \"\") : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"primary_network_interface\" {\n")
            .append("        for_each = length(trim(lookup(each.value, \"network_interface_id\", \"\"), \" \")) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            network_interface_id  = length(trim(lookup(each.value, \"network_interface_id\", \"\"), \" \")) > 0 ? lookup(each.value, \"network_interface_id\", \"\") : null\n")
            .append("            delete_on_termination = length(trim(lookup(each.value, \"pri_eni_delete_on_termination\", \"\"), \" \")) > 0 ? lookup(each.value, \"pri_eni_delete_on_termination\", \"\") == \"true\" ? true : false : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"capacity_reservation_specification\" {\n")
            .append("        for_each = length(compact([\n")
            .append("            lookup(each.value, \"capacity_reservation_preference\", null),\n")
            .append("            lookup(each.value, \"capacity_reservation_id\", null),\n")
            .append("            lookup(each.value, \"capacity_reservation_resource_group_arn\", null)\n")
            .append("        ])) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            capacity_reservation_preference = length(trim(lookup(each.value, \"capacity_reservation_preference\", \"\"), \" \")) > 0 ? lookup(each.value, \"capacity_reservation_preference\", \"\") : null\n")
            .append("            capacity_reservation_target {\n")
            .append("                capacity_reservation_id                 = length(trim(lookup(each.value, \"capacity_reservation_id\", \"\"), \" \")) > 0 ? lookup(each.value, \"capacity_reservation_id\", \"\") : null\n")
            .append("                capacity_reservation_resource_group_arn = length(trim(lookup(each.value, \"capacity_reservation_resource_group_arn\", \"\"), \" \")) > 0 ? lookup(each.value, \"capacity_reservation_resource_group_arn\", \"\") : null\n")
            .append("            }\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"cpu_options\" {\n")
            .append("        for_each = length(compact([\n")
            .append("            lookup(each.value, \"amd_sev_snp\", null),\n")
            .append("            lookup(each.value, \"core_count\", null),\n")
            .append("            lookup(each.value, \"nested_virtualization\", null),\n")
            .append("            lookup(each.value, \"threads_per_core\", null)\n")
            .append("        ])) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            amd_sev_snp           = length(trim(lookup(each.value, \"amd_sev_snp\", \"\"), \" \")) > 0 ? lookup(each.value, \"amd_sev_snp\", \"\") : null\n")
            .append("            nested_virtualization = length(trim(lookup(each.value, \"nested_virtualization\", \"\"), \" \")) > 0 ? lookup(each.value, \"nested_virtualization\", \"\") : null\n")
            .append("            core_count            = length(trim(lookup(each.value, \"core_count\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"core_count\", \"\")), null) : null\n")
            .append("            threads_per_core      = length(trim(lookup(each.value, \"threads_per_core\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"threads_per_core\", \"\")), null) : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"credit_specification\" {\n")
            .append("        for_each = length(trim(lookup(each.value, \"cpu_credits\", \"\"), \" \")) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            cpu_credits = length(trim(lookup(each.value, \"cpu_credits\", \"\"), \" \")) > 0 ? lookup(each.value, \"cpu_credits\", \"\") : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"enclave_options\" {\n")
            .append("        for_each = length(trim(lookup(each.value, \"enabled\", \"\"), \" \")) > 0 ? lookup(each.value, \"enabled\", \"\") == \"true\" ? [1] : [] : []\n")
            .append("        content {\n")
            .append("            enabled = length(trim(lookup(each.value, \"enabled\", \"\"), \" \")) > 0 ? lookup(each.value, \"enabled\", \"\") == \"true\" ? true : false : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"maintenance_options\" {\n")
            .append("        for_each = length(trim(lookup(each.value, \"auto_recovery\", \"\"), \" \")) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            auto_recovery = length(trim(lookup(each.value, \"auto_recovery\", \"\"), \" \")) > 0 ? lookup(each.value, \"auto_recovery\", \"\") : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"metadata_options\" {\n")
            .append("        for_each = length(compact([\n")
            .append("            lookup(each.value, \"http_endpoint\", null),\n")
            .append("            lookup(each.value, \"http_protocol_ipv6\", null),\n")
            .append("            lookup(each.value, \"http_put_response_hop_limit\", null),\n")
            .append("            lookup(each.value, \"http_tokens\", null),\n")
            .append("            lookup(each.value, \"instance_metadata_tags\", null)\n")
            .append("        ])) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            http_endpoint               = length(trim(lookup(each.value, \"http_endpoint\", \"\"), \" \")) > 0 ? lookup(each.value, \"http_endpoint\", \"\") : null\n")
            .append("            http_protocol_ipv6          = length(trim(lookup(each.value, \"http_protocol_ipv6\", \"\"), \" \")) > 0 ? lookup(each.value, \"http_protocol_ipv6\", \"\") : null\n")
            .append("            http_tokens                 = length(trim(lookup(each.value, \"http_tokens\", \"\"), \" \")) > 0 ? lookup(each.value, \"http_tokens\", \"\") : null\n")
            .append("            instance_metadata_tags      = length(trim(lookup(each.value, \"instance_metadata_tags\", \"\"), \" \")) > 0 ? lookup(each.value, \"instance_metadata_tags\", \"\") : null\n")
            .append("            http_put_response_hop_limit = length(trim(lookup(each.value, \"http_put_response_hop_limit\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"http_put_response_hop_limit\", \"\")), null) : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"private_dns_name_options\" {\n")
            .append("        for_each = length([\n")
            .append("            for v in [\n")
            .append("                lookup(each.value, \"enable_resource_name_dns_aaaa_record\", null),\n")
            .append("                lookup(each.value, \"enable_resource_name_dns_a_record\", null),\n")
            .append("                lookup(each.value, \"hostname_type\", null)\n")
            .append("            ] : v\n")
            .append("            if v != null && v != \"\"\n")
            .append("        ]) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            enable_resource_name_dns_aaaa_record = length(trim(lookup(each.value, \"enable_resource_name_dns_aaaa_record\", \"\"), \" \")) > 0 ? lookup(each.value, \"enable_resource_name_dns_aaaa_record\", \"\") == \"true\" ? true : false : null\n")
            .append("            enable_resource_name_dns_a_record    = length(trim(lookup(each.value, \"enable_resource_name_dns_a_record\", \"\"), \" \")) > 0 ? lookup(each.value, \"enable_resource_name_dns_a_record\", \"\") == \"true\" ? true : false : null\n")
            .append("            hostname_type                        = length(trim(lookup(each.value, \"hostname_type\", \"\"), \" \")) > 0 ? lookup(each.value, \"hostname_type\", \"\") : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"root_block_device\" {\n")
            .append("        for_each = length([\n")
            .append("            for v in [\n")
            .append("                lookup(each.value, \"root_dev_delete_on_termination\", null),\n")
            .append("                lookup(each.value, \"root_dev_encrypted\", null),\n")
            .append("                lookup(each.value, \"root_dev_iops\", null),\n")
            .append("                lookup(each.value, \"root_dev_throughput\", null),\n")
            .append("                lookup(each.value, \"root_dev_volume_size\", null),\n")
            .append("                lookup(each.value, \"root_dev_kms_key_id\", null),\n")
            .append("                lookup(each.value, \"root_dev_volume_type\", null),\n")
            .append("                lookup(each.value, \"root_dev_tags\", null)\n")
            .append("            ] : v\n")
            .append("            if v != null && v != \"\"\n")
            .append("        ]) > 0 ? [1] : []\n")
            .append("        content {\n")
            .append("            delete_on_termination = length(trim(lookup(each.value, \"root_dev_delete_on_termination\", \"\"), \" \")) > 0 ? lookup(each.value, \"root_dev_delete_on_termination\", \"\") == \"true\" ? true : false : null\n")
            .append("            encrypted             = length(trim(lookup(each.value, \"root_dev_encrypted\", \"\"), \" \")) > 0 ? lookup(each.value, \"root_dev_encrypted\", \"\") == \"true\" ? true : false : null\n")
            .append("            iops                  = length(trim(lookup(each.value, \"root_dev_iops\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"root_dev_iops\", \"\")), null) : null\n")
            .append("            throughput            = length(trim(lookup(each.value, \"root_dev_throughput\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"root_dev_throughput\", \"\")), null) : null\n")
            .append("            volume_size           = length(trim(lookup(each.value, \"root_dev_volume_size\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"root_dev_volume_size\", \"\")), null) : null\n")
            .append("            kms_key_id            = length(trim(lookup(each.value, \"root_dev_kms_key_id\", \"\"), \" \")) > 0 ? lookup(each.value, \"root_dev_kms_key_id\", \"\") : null\n")
            .append("            volume_type           = length(trim(lookup(each.value, \"root_dev_volume_type\", \"\"), \" \")) > 0 ? lookup(each.value, \"root_dev_volume_type\", \"\") : null\n")
            .append("            tags                  = length(trim(lookup(each.value, \"root_dev_tags\", \"\"), \" \")) > 0 ? merge({ for index, tag in split(\"{{__,__}}\", lookup(each.value, \"root_dev_tags\", \"\")) : element(split(\"{{__:__}}\", tag), 0) => element(split(\"{{__:__}}\", tag), 1) }) : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"ebs_block_device\" {\n")
            .append("        for_each = zipmap(range(length(compact(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_device_name\", \"\"))))), compact(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_device_name\", \"\"))))\n")
            .append("        content {\n")
            .append("            device_name           = ebs_block_device.value\n")
            .append("            kms_key_id            = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_kms_key_id\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_kms_key_id\", \"\")), ebs_block_device.key), \"\") : null\n")
            .append("            snapshot_id           = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_snapshot_id\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_snapshot_id\", \"\")), ebs_block_device.key), \"\") : null\n")
            .append("            volume_type           = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_volume_type\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_volume_type\", \"\")), ebs_block_device.key), \"\") : null\n")
            .append("            iops                  = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_iops\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? try(tonumber(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_iops\", \"\")), ebs_block_device.key), \"\")), null) : null\n")
            .append("            throughput            = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_throughput\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? try(tonumber(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_throughput\", \"\")), ebs_block_device.key), \"\")), null) : null\n")
            .append("            volume_size           = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_volume_size\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? try(tonumber(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_volume_size\", \"\")), ebs_block_device.key), \"\")), null) : null\n")
            .append("            delete_on_termination = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_delete_on_termination\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_delete_on_termination\", \"\")), ebs_block_device.key), \"\") == \"true\" ? true : false : null\n")
            .append("            encrypted             = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_encrypted\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"ebs_dev_encrypted\", \"\")), ebs_block_device.key), \"\") == \"true\" ? true : false : null\n")
            .append("            tags                  = length(trim(try(element(split(\"{{__/__}}\", lookup(each.value, \"ebs_dev_tags\", \"\")), ebs_block_device.key), \"\"), \" \")) > 0 ? merge({ for index, tag in split(\"{{__,__}}\", try(element(split(\"{{__/__}}\", lookup(each.value, \"ebs_dev_tags\", \"\")), ebs_block_device.key), \"\")) : element(split(\"{{__:__}}\", tag), 0) => element(split(\"{{__:__}}\", tag), 1) }) : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"ephemeral_block_device\" {\n")
            .append("        for_each = zipmap(range(length(compact(split(\"{{__,__}}\", lookup(each.value, \"eph_dev_device_name\", \"\"))))), compact(split(\"{{__,__}}\", lookup(each.value, \"eph_dev_device_name\", \"\"))))\n")
            .append("        content {\n")
            .append("            device_name  = ephemeral_block_device.value\n")
            .append("            virtual_name = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"virtual_name\", \"\")), ephemeral_block_device.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"virtual_name\", \"\")), ephemeral_block_device.key), \"\") : null\n")
            .append("            no_device    = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"no_device\", \"\")), ephemeral_block_device.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"no_device\", \"\")), ephemeral_block_device.key), \"\") == \"true\" ? true : false : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    dynamic \"secondary_network_interface\" {\n")
            .append("        for_each = zipmap(range(length(compact(split(\"{{__,__}}\", lookup(each.value, \"secondary_subnet_id\", \"\"))))), compact(split(\"{{__,__}}\", lookup(each.value, \"secondary_subnet_id\", \"\"))))\n")
            .append("        content {\n")
            .append("            secondary_subnet_id      = secondary_network_interface.value\n")
            .append("            interface_type           = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"interface_type\", \"\")), secondary_network_interface.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"interface_type\", \"\")), secondary_network_interface.key), \"\") : null\n")
            .append("            network_card_index       = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"network_card_index\", \"\")), secondary_network_interface.key), \"\"), \" \")) > 0 ? try(tonumber(try(element(split(\"{{__,__}}\", lookup(each.value, \"network_card_index\", \"\")), secondary_network_interface.key), \"\")), null) : null\n")
            .append("            device_index             = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"device_index\", \"\")), secondary_network_interface.key), \"\"), \" \")) > 0 ? try(tonumber(try(element(split(\"{{__,__}}\", lookup(each.value, \"device_index\", \"\")), secondary_network_interface.key), \"\")), null) : null\n")
            .append("            private_ip_address_count = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"private_ip_address_count\", \"\")), secondary_network_interface.key), \"\"), \" \")) > 0 ? try(tonumber(try(element(split(\"{{__,__}}\", lookup(each.value, \"private_ip_address_count\", \"\")), secondary_network_interface.key), \"\")), null) : null\n")
            .append("            delete_on_termination    = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"sec_eni_delete_on_termination\", \"\")), secondary_network_interface.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"sec_eni_delete_on_termination\", \"\")), secondary_network_interface.key), \"\") == \"true\" ? true : false : null\n")
            .append("            private_ip_addresses     = length(try(compact(split(\"{{__,__}}\", element(split(\"{{__/__}}\", lookup(each.value, \"private_ip_addresses\", \"\")), secondary_network_interface.key))), \"\")) > 0 ? try(compact(split(\"{{__,__}}\", element(split(\"{{__/__}}\", lookup(each.value, \"private_ip_addresses\", \"\")), secondary_network_interface.key))), \"\") : null\n")
            .append("        }\n")
            .append("    }\n")
            .append("    volume_tags = length(trim(lookup(each.value, \"volume_tags\", \"\"), \" \")) > 0 ? merge({ for index, volume_tag in split(\"{{__,__}}\", lookup(each.value, \"volume_tags\", \"\")) : element(split(\"{{__:__}}\", volume_tag), 0) => element(split(\"{{__:__}}\", volume_tag), 1) }) : null\n")

            /** End of Reusable Terraform Module Code Substitution */

            .append("    tags = length(trim(lookup(each.value, \"tags\", \"\"), \" \")) > 0 ? merge({ for index, tag in split(\"{{__,__}}\", lookup(each.value, \"tags\", \"\")) : element(split(\"{{__:__}}\", tag), 0) => element(split(\"{{__:__}}\", tag), 1) }) : null\n\n")
            .append("    lifecycle {\n")
            .append("        ignore_changes = [\n")
            .append("        ]\n")
            .append("    }\n")
            .append("}\n");
        return definedMainFile.toString();
    }
}
