package click.opentofu.sprout.handler.tofu.resource.implementations;

import org.springframework.stereotype.Component;

import click.opentofu.sprout.handler.tofu.resource.interfaces.ResourceHandler;

@Component("tofu_resource")
public class TofuResource implements ResourceHandler {
    @Override
    public String buildTofuResourceMainFile(String region, String account) {
        StringBuilder definedMainFile = new StringBuilder();
        definedMainFile
            .append("variable aws_sprout { type = map(map(any)) }\n\n")
            .append("resource aws_sprout product {\n")
            .append("    for_each = var.aws_sprout\n\n")

            /** Start of Reusable Terraform Module Code Substitution */

            .append("    container_definitions    = length(trim(lookup(each.value, \"container_definitions\", \"\"), \" \")) > 0 ? file(lookup(each.value, \"container_definitions\", \"\")) : \"\"\n")
            .append("    cpu                      = length(trim(lookup(each.value, \"cpu\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"cpu\", \"\")), null) : null\n")
            .append("    enable_fault_injection   = length(trim(lookup(each.value, \"enable_fault_injection\", \"\"), \" \")) > 0 ? lookup(each.value, \"enable_fault_injection\", \"false\") == \"true\" ? true : false : null\n")
            .append("    execution_role_arn       = length(trim(lookup(each.value, \"execution_role_arn\", \"\"), \" \")) > 0 ? lookup(each.value, \"execution_role_arn\", \"\") : null\n")
            .append("    family                   = length(trim(lookup(each.value, \"family\", \"\"), \" \")) > 0 ? lookup(each.value, \"family\", \"\") : null\n")
            .append("    ipc_mode                 = length(trim(lookup(each.value, \"ipc_mode\", \"\"), \" \")) > 0 ? lookup(each.value, \"ipc_mode\", \"\") : null\n")
            .append("    memory                   = length(trim(lookup(each.value, \"memory\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"memory\", \"\")), null) : null\n")
            .append("    network_mode             = length(trim(lookup(each.value, \"network_mode\", \"\"), \" \")) > 0 ? lookup(each.value, \"network_mode\", \"\") : null\n")
            .append("    pid_mode                 = length(trim(lookup(each.value, \"pid_mode\", \"\"), \" \")) > 0 ? lookup(each.value, \"pid_mode\", \"\") : null\n")
            .append("    region                   = length(trim(lookup(each.value, \"region\", \"\"), \" \")) > 0 ? lookup(each.value, \"region\", \"\") : null\n")
            .append("    requires_compatibilities = length(trim(lookup(each.value, \"requires_compatibilities\", \"\"), \" \")) > 0 ? compact(split(\"{{__,__}}\", lookup(each.value, \"requires_compatibilities\", \"\"))) : null\n")
            .append("    skip_destroy             = length(trim(lookup(each.value, \"skip_destroy\", \"\"), \" \")) > 0 ? lookup(each.value, \"skip_destroy\", \"false\") == \"true\" ? true : false : null\n")
            .append("    task_role_arn            = length(trim(lookup(each.value, \"task_role_arn\", \"\"), \" \")) > 0 ? lookup(each.value, \"task_role_arn\", \"\") : null\n")
            .append("    track_latest             = length(trim(lookup(each.value, \"track_latest\", \"\"), \" \")) > 0 ? lookup(each.value, \"track_latest\", \"false\") == \"true\" ? true : false : null\n\n")
            .append("    dynamic \"ephemeral_storage\" {\n")
            .append("        for_each = length(trim(lookup(each.value, \"size_in_gib\", \"\"), \" \")) > 0 ? [1] : []\n\n")
            .append("        content {\n")
            .append("            size_in_gib = try(tonumber(lookup(each.value, \"size_in_gib\", \"\")), 21)\n")
            .append("        }\n")
            .append("    }\n\n")
            .append("    dynamic \"placement_constraints\" {\n")
            .append("        for_each = zipmap(range(length(compact(split(\"{{__,__}}\", lookup(each.value, \"constraints_type\", \"\"))))), compact(split(\"{{__,__}}\", lookup(each.value, \"constraints_type\", \"\"))))\n\n")
            .append("        content {\n")
            .append("            type       = placement_constraints.value\n")
            .append("            expression = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"expression\", \"\")), placement_constraints.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"expression\", \"\")), placement_constraints.key), \"\") : null\n")
            .append("        }\n")
            .append("    }\n\n")
            .append("    proxy_configuration {\n")
            .append("        container_name = length(trim(lookup(each.value, \"container_name\", \"\"), \" \")) > 0 ? lookup(each.value, \"container_name\", \"\") : null\n")
            .append("        type           = length(trim(lookup(each.value, \"proxy_type\", \"\"), \" \")) > 0 ? lookup(each.value, \"proxy_type\", \"APPMESH\") : null\n\n")
            .append("        properties = {\n")
            .append("            AppPorts         = length(trim(lookup(each.value, \"AppPorts\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"AppPorts\", \"\")), null) : null\n")
            .append("            EgressIgnoredIPs = length(trim(lookup(each.value, \"EgressIgnoredIPs\", \"\"), \" \")) > 0 ? lookup(each.value, \"EgressIgnoredIPs\", \"\") : null\n")
            .append("            IgnoredUID       = length(trim(lookup(each.value, \"IgnoredUID\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"IgnoredUID\", \"\")), null) : null\n")
            .append("            ProxyEgressPort  = length(trim(lookup(each.value, \"ProxyEgressPort\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"ProxyEgressPort\", \"\")), null) : null\n")
            .append("            ProxyIngressPort = length(trim(lookup(each.value, \"ProxyIngressPort\", \"\"), \" \")) > 0 ? try(tonumber(lookup(each.value, \"ProxyIngressPort\", \"\")), null) : null\n")
            .append("        }\n")
            .append("    }\n\n")
            .append("    runtime_platform {\n")
            .append("        operating_system_family = length(trim(lookup(each.value, \"operating_system_family\", \"\"), \" \")) > 0 ? lookup(each.value, \"operating_system_family\", \"\") : null\n")
            .append("        cpu_architecture        = length(trim(lookup(each.value, \"cpu_architecture\", \"\"), \" \")) > 0 ? lookup(each.value, \"cpu_architecture\", \"\") : null\n")
            .append("    }\n\n")
            .append("    dynamic \"volume\" {\n")
            .append("        for_each = zipmap(range(length(compact(split(\"{{__,__}}\", lookup(each.value, \"volume_name\", \"\"))))), compact(split(\"{{__,__}}\", lookup(each.value, \"volume_name\", \"\"))))\n\n")
            .append("        content {\n")
            .append("            name                = volume.value\n")
            .append("            host_path           = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"host_path\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"host_path\", \"\")), volume.key), \"\") : null\n")
            .append("            configure_at_launch = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"configure_at_launch\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"configure_at_launch\", \"\")), volume.key), \"false\") == \"true\" ? true : false : null\n\n")
            .append("            dynamic \"docker_volume_configuration\" {\n")
            .append("                for_each = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"driver\", \"\")), volume.key), \"\"), \" \")) > 0 ? [1] : []\n\n")
            .append("                content {\n")
            .append("                    autoprovision = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"autoprovision\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"autoprovision\", \"\")), volume.key), \"false\") == \"true\" ? true : false : null\n")
            .append("                    driver        = try(element(split(\"{{__,__}}\", lookup(each.value, \"driver\", \"\")), volume.key), \"local\")\n")
            .append("                    scope         = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"scope\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"scope\", \"\")), volume.key), \"shared\") : null\n")
            .append("                    labels        = length(trim(try(element(split(\"{{__/__}}\", lookup(each.value, \"labels\", \"\")), volume.key), \"\"), \" \")) > 0 ? merge({ for index, tag in split(\"{{__,__}}\", try(element(split(\"{{__/__}}\", lookup(each.value, \"labels\", \"\")), volume.key), \"\")) : element(split(\"{{__:__}}\", tag), 0) => element(split(\"{{__:__}}\", tag), 1) }) : null\n")
            .append("                    driver_opts   = length(trim(try(element(split(\"{{__/__}}\", lookup(each.value, \"driver_opts\", \"\")), volume.key), \"\"), \" \")) > 0 ? merge({ for index, tag in split(\"{{__,__}}\", try(element(split(\"{{__/__}}\", lookup(each.value, \"driver_opts\", \"\")), volume.key), \"\")) : element(split(\"{{__:__}}\", tag), 0) => element(split(\"{{__:__}}\", tag), 1) }) : null\n")
            .append("                }\n")
            .append("            }\n\n")
            .append("            dynamic \"efs_volume_configuration\" {\n")
            .append("                for_each = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"efs_file_system_id\", \"\")), volume.key), \"\"), \" \")) > 0 ? [1] : []\n\n")
            .append("                content {\n")
            .append("                    file_system_id          = try(element(split(\"{{__,__}}\", lookup(each.value, \"efs_file_system_id\", \"\")), volume.key), \"\")\n")
            .append("                    root_directory          = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"efs_root_directory\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"efs_root_directory\", \"\")), volume.key), \"/\") : null\n")
            .append("                    transit_encryption      = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"transit_encryption\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"transit_encryption\", \"\")), volume.key), \"DISABLED\") : null\n")
            .append("                    transit_encryption_port = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"transit_encryption_port\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(tonumber(try(element(split(\"{{__,__}}\", lookup(each.value, \"transit_encryption_port\", \"\")), volume.key), \"\")), null) : null\n\n")
            .append("                    authorization_config {\n")
            .append("                        access_point_id = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"access_point_id\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"access_point_id\", \"\")), volume.key), \"\") : null\n")
            .append("                        iam             = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"iam\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"iam\", \"\")), volume.key), \"DISABLED\") : null\n")
            .append("                    }\n")
            .append("                }\n")
            .append("            }\n\n")
            .append("            dynamic \"fsx_windows_file_server_volume_configuration\" {\n")
            .append("                for_each = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"fsx_file_system_id\", \"\")), volume.key), \"\"), \" \")) > 0 ? [1] : []\n\n")
            .append("                content {\n")
            .append("                    file_system_id = try(element(split(\"{{__,__}}\", lookup(each.value, \"fsx_file_system_id\", \"\")), volume.key), \"\")\n")
            .append("                    root_directory = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"fsx_root_directory\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"fsx_root_directory\", \"\")), volume.key), \"\") : null\n\n")
            .append("                    authorization_config {\n")
            .append("                        credentials_parameter = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"credentials_parameter\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"credentials_parameter\", \"\")), volume.key), \"\") : null\n")
            .append("                        domain                = length(trim(try(element(split(\"{{__,__}}\", lookup(each.value, \"domain\", \"\")), volume.key), \"\"), \" \")) > 0 ? try(element(split(\"{{__,__}}\", lookup(each.value, \"domain\", \"\")), volume.key), \"\") : null\n")
            .append("                    }\n")
            .append("                }\n")
            .append("            }\n")
            .append("        }\n")
            .append("    }\n")

            /** End of Reusable Terraform Module Code Substitution */

            .append("    tags = length(trim(lookup(each.value, \"tags\", \"\"), \" \")) > 0 ? merge({ for index, tag in split(\"{{__,__}}\", lookup(each.value, \"tags\", \"\")) : element(split(\"{{__:__}}\", tag), 0) => element(split(\"{{__:__}}\", tag), 1) }) : null\n\n")
            .append("    lifecycle {\n")
            .append("        ignore_changes = [\n")
            .append("        ]\n")
            .append("    }\n")
            .append("}\n");
        return definedMainFile.toString();
    }
}
