package click.opentofu.sprout.handler.python.implementations;

import org.springframework.stereotype.Component;

import click.opentofu.sprout.handler.python.interfaces.PythonHandler;

@Component("boto3_sprout")
public class AwsEcsTaskDefinitionBoto implements PythonHandler {
    @Override
    public String buildAwsPythonFile(String ROOT_PATH, String authEmailId, String uuid, String region, String awsAccessKey, String awsSecretAccessKey, String awsSessionToken) {
        StringBuilder definedPythonFile = new StringBuilder();
        definedPythonFile
            .append("import boto3\n")
            .append("import botocore.exceptions\n")
            .append("from botocore.exceptions import ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError\n")
            .append("import json\n")
            .append("from datetime import datetime\n")
            .append("import base64\n")
            .append("import sys\n")
            .append("from collections import defaultdict\n")
            .append("aws_access_key = '" + awsAccessKey + "'\n")
            .append("aws_secret_key = '" + awsSecretAccessKey + "'\n")
            .append("aws_session_token = '" + awsSessionToken + "'\n")
            .append("session = boto3.Session(\n")
            .append("    region_name='" + region + "',\n")
            .append("    aws_access_key_id=aws_access_key,\n")
            .append("    aws_secret_access_key=aws_secret_key,\n")
            .append("    aws_session_token=aws_session_token\n")
            .append(")\n")

            /** Start of Substitution */

            .append("ecs = session.client('ecs')\n")
            .append("sts = session.client('sts')\n")
            .append("try: \n")
            .append("    caller_identity = sts.get_caller_identity()\n")
            .append("    account_id = caller_identity['Account'] if 'Account' in caller_identity else ''\n")
            .append("except ClientError as e:\n")
            .append("    if e.response['Error']['Code'] == 'ExpiredToken':\n")
            .append("        print('ERROR: AWS temporary credentials expired')\n")
            .append("        sys.exit(1)\n")
            .append("    else:\n")
            .append("        account_id = ''\n")
            .append("except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError): account_id = ''\n")
            .append("aws_sprout_details = {'outputs': {'aws_sprout': {'value': {}}}}\n")
            .append("arn_token = None\n")
            .append("while True:\n")
            .append("    try: arn_response = ecs.list_task_definitions(nextToken=arn_token) if arn_token else ecs.list_task_definitions()\n")
            .append("    except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError): arn_response = {}\n")
            .append("    for arn in (arn_response['taskDefinitionArns'] if 'taskDefinitionArns' in arn_response else []):\n")
            .append("        try: task_response = ecs.describe_task_definition(taskDefinition=arn)\n")
            .append("        except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError): task_response = {}\n")
            .append("        definition = task_response['taskDefinition'] if 'taskDefinition' in task_response else {}\n\n")
            .append("        task_arn = definition['taskDefinitionArn'] if 'taskDefinitionArn' in definition else ''\n")
            .append("        task_id = task_arn.split('/')[-1].replace(':', '-')\n\n")
            .append("        try: tag_response = ecs.list_tags_for_resource(resourceArn=task_arn)\n")
            .append("        except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError): tag_response = {}\n\n")
            .append("        container_definitions = definition['containerDefinitions'] if 'containerDefinitions' in definition else []\n")
            .append("        cpu = definition['cpu'] if 'cpu' in definition else ''\n")
            .append("        enable_fault_injection = definition['enableFaultInjection'] if 'enableFaultInjection' in definition else False\n")
            .append("        size_in_gib = definition['ephemeralStorage']['sizeInGiB'] if 'ephemeralStorage' in definition and 'sizeInGiB' in definition['ephemeralStorage'] else ''\n")
            .append("        execution_role_arn = definition['executionRoleArn'] if 'executionRoleArn' in definition else ''\n")
            .append("        family = definition['family'] if 'family' in definition else ''\n")
            .append("        ipc_mode = definition['ipcMode'] if 'ipcMode' in definition else ''\n")
            .append("        memory = definition['memory'] if 'memory' in definition else ''\n")
            .append("        network_mode = definition['networkMode'] if 'networkMode' in definition else ''\n")
            .append("        pid_mode = definition['pidMode'] if 'pidMode' in definition else ''\n")
            .append("        expression = [ placementConstraint['expression'] if 'expression' in placementConstraint else '' for placementConstraint in (definition['placementConstraints'] if 'placementConstraints' in definition else []) ]\n")
            .append("        constraints_type = [ placementConstraint['type'] for placementConstraint in (definition['placementConstraints'] if 'placementConstraints' in definition else []) if 'type' in placementConstraint ]\n")
            .append("        container_name = definition['proxyConfiguration']['containerName'] if 'proxyConfiguration' in definition and 'containerName' in definition['proxyConfiguration'] else ''\n")
            .append("        proxy_type = definition['proxyConfiguration']['type'] if 'proxyConfiguration' in definition and 'type' in definition['proxyConfiguration'] else ''\n")
            .append("        app_ports = next((propertie['value'] for propertie in (definition['proxyConfiguration']['properties'] if 'proxyConfiguration' in definition and 'properties' in definition['proxyConfiguration'] else []) if 'value' in propertie and 'name' in propertie and propertie['name'] == 'AppPorts'), '')\n")
            .append("        egress_ignored_ips = next((propertie['value'] for propertie in (definition['proxyConfiguration']['properties'] if 'proxyConfiguration' in definition and 'properties' in definition['proxyConfiguration'] else []) if 'value' in propertie and 'name' in propertie and propertie['name'] == 'EgressIgnoredIPs'), '')\n")
            .append("        ignored_uid = next((propertie['value'] for propertie in (definition['proxyConfiguration']['properties'] if 'proxyConfiguration' in definition and 'properties' in definition['proxyConfiguration'] else []) if 'value' in propertie and 'name' in propertie and propertie['name'] == 'IgnoredUID'), '')\n")
            .append("        proxy_egress_port = next((propertie['value'] for propertie in (definition['proxyConfiguration']['properties'] if 'proxyConfiguration' in definition and 'properties' in definition['proxyConfiguration'] else []) if 'value' in propertie and 'name' in propertie and propertie['name'] == 'ProxyEgressPort'), '')\n")
            .append("        proxy_ingress_port = next((propertie['value'] for propertie in (definition['proxyConfiguration']['properties'] if 'proxyConfiguration' in definition and 'properties' in definition['proxyConfiguration'] else []) if 'value' in propertie and 'name' in propertie and propertie['name'] == 'ProxyIngressPort'), '')\n")
            .append("        requires_compatibilities = definition['requiresCompatibilities'] if 'requiresCompatibilities' in definition else []\n")
            .append("        operating_system_family = definition['runtimePlatform']['operatingSystemFamily'] if 'runtimePlatform' in definition and 'operatingSystemFamily' in definition['runtimePlatform'] else ''\n")
            .append("        cpu_architecture = definition['runtimePlatform']['cpuArchitecture'] if 'runtimePlatform' in definition and 'cpuArchitecture' in definition['runtimePlatform'] else ''\n")
            .append("        skip_destroy = ''\n")
            .append("        task_role_arn = definition['taskRoleArn'] if 'taskRoleArn' in definition else ''\n")
            .append("        track_latest = ''\n")
            .append("        volume_name = [ volume['name'] for volume in (definition['volumes'] if 'volumes' in definition else []) if 'name' in volume ]\n")
            .append("        host_path = [ volume['host']['sourcePath'] if 'sourcePath' in volume['host'] else '' for volume in (definition['volumes'] if 'volumes' in definition else []) if 'host' in volume ]\n")
            .append("        configure_at_launch = [ volume['configuredAtLaunch'] for volume in (definition['volumes'] if 'volumes' in definition else []) if 'configuredAtLaunch' in volume ]\n")
            .append("        autoprovision = [ volume['dockerVolumeConfiguration']['autoprovision'] for volume in (definition['volumes'] if 'volumes' in definition else []) if 'dockerVolumeConfiguration' in volume and 'autoprovision' in volume['dockerVolumeConfiguration'] ]\n")
            .append("        driver = [ volume['dockerVolumeConfiguration']['driver'] if 'driver' in volume['dockerVolumeConfiguration'] else '' for volume in (definition['volumes'] if 'volumes' in definition else []) if 'dockerVolumeConfiguration' in volume ]\n")
            .append("        scope = [ volume['dockerVolumeConfiguration']['scope'] if 'scope' in volume['dockerVolumeConfiguration'] else '' for volume in (definition['volumes'] if 'volumes' in definition else []) if 'dockerVolumeConfiguration' in volume ]\n")
            .append("        labels = [ volume['dockerVolumeConfiguration']['labels'] if 'labels' in volume['dockerVolumeConfiguration'] else {} for volume in (definition['volumes'] if 'volumes' in definition else []) if 'dockerVolumeConfiguration' in volume ]\n")
            .append("        driver_opts = [ volume['dockerVolumeConfiguration']['driverOpts'] if 'driverOpts' in volume['dockerVolumeConfiguration'] else {} for volume in (definition['volumes'] if 'volumes' in definition else []) if 'dockerVolumeConfiguration' in volume ]\n")
            .append("        efs_file_system_id = [ volume['efsVolumeConfiguration']['fileSystemId'] for volume in (definition['volumes'] if 'volumes' in definition else []) if 'efsVolumeConfiguration' in volume and 'fileSystemId' in volume['efsVolumeConfiguration'] ]\n")
            .append("        efs_root_directory = [ volume['efsVolumeConfiguration']['rootDirectory'] if 'rootDirectory' in volume['efsVolumeConfiguration'] else '' for volume in (definition['volumes'] if 'volumes' in definition else []) if 'efsVolumeConfiguration' in volume ]\n")
            .append("        transit_encryption = [ volume['efsVolumeConfiguration']['transitEncryption'] if 'transitEncryption' in volume['efsVolumeConfiguration'] else '' for volume in (definition['volumes'] if 'volumes' in definition else []) if 'efsVolumeConfiguration' in volume ]\n")
            .append("        transit_encryption_port = [ volume['efsVolumeConfiguration']['transitEncryptionPort'] if 'transitEncryptionPort' in volume['efsVolumeConfiguration'] else '' for volume in (definition['volumes'] if 'volumes' in definition else []) if 'efsVolumeConfiguration' in volume ]\n")
            .append("        access_point_id = [ volume['efsVolumeConfiguration']['authorizationConfig']['accessPointId'] if 'accessPointId' in volume['efsVolumeConfiguration']['authorizationConfig'] else '' for volume in (definition['volumes'] if 'volumes' in definition else []) if 'efsVolumeConfiguration' in volume and 'authorizationConfig' in volume['efsVolumeConfiguration'] ]\n")
            .append("        iam = [ volume['efsVolumeConfiguration']['authorizationConfig']['iam'] if 'iam' in volume['efsVolumeConfiguration']['authorizationConfig'] else '' for volume in (definition['volumes'] if 'volumes' in definition else []) if 'efsVolumeConfiguration' in volume and 'authorizationConfig' in volume['efsVolumeConfiguration'] ]\n")
            .append("        fsx_file_system_id = [ volume['fsxWindowsFileServerVolumeConfiguration']['fileSystemId'] for volume in (definition['volumes'] if 'volumes' in definition else []) if 'fsxWindowsFileServerVolumeConfiguration' in volume and 'fileSystemId' in volume['fsxWindowsFileServerVolumeConfiguration'] ]\n")
            .append("        fsx_root_directory = [ volume['fsxWindowsFileServerVolumeConfiguration']['rootDirectory'] for volume in (definition['volumes'] if 'volumes' in definition else []) if 'fsxWindowsFileServerVolumeConfiguration' in volume and 'rootDirectory' in volume['fsxWindowsFileServerVolumeConfiguration'] ]\n")
            .append("        credentials_parameter = [ volume['fsxWindowsFileServerVolumeConfiguration']['authorizationConfig']['credentialsParameter'] for volume in (definition['volumes'] if 'volumes' in definition else []) if 'fsxWindowsFileServerVolumeConfiguration' in volume and 'authorizationConfig' in volume['fsxWindowsFileServerVolumeConfiguration'] and 'credentialsParameter' in volume['fsxWindowsFileServerVolumeConfiguration']['authorizationConfig'] ]\n")
            .append("        domain = [ volume['fsxWindowsFileServerVolumeConfiguration']['authorizationConfig']['domain'] for volume in (definition['volumes'] if 'volumes' in definition else []) if 'fsxWindowsFileServerVolumeConfiguration' in volume and 'authorizationConfig' in volume['fsxWindowsFileServerVolumeConfiguration'] and 'domain' in volume['fsxWindowsFileServerVolumeConfiguration']['authorizationConfig'] ]\n\n")
            .append("        tags = { tag['key']: tag['value'] for tag in (tag_response['tags'] if 'tags' in tag_response else []) if 'key' in tag and 'value' in tag }\n\n")
            .append("        sprout_details = {\n")
            .append("            'account_id': account_id,\n")
            .append("            'region': '" + region + "',\n")
            .append("            'task_arn': task_arn,\n")
            .append("            'task_id': task_id,\n")
            .append("            'container_definitions': container_definitions,\n")
            .append("            'cpu': cpu,\n")
            .append("            'enable_fault_injection': enable_fault_injection,\n")
            .append("            'size_in_gib': size_in_gib,\n")
            .append("            'execution_role_arn': execution_role_arn,\n")
            .append("            'family': family,\n")
            .append("            'ipc_mode': ipc_mode,\n")
            .append("            'memory': memory,\n")
            .append("            'network_mode': network_mode,\n")
            .append("            'pid_mode': pid_mode,\n")
            .append("            'expression': expression,\n")
            .append("            'constraints_type': constraints_type,\n")
            .append("            'container_name': container_name,\n")
            .append("            'proxy_type': proxy_type,\n")
            .append("            'app_ports': app_ports,\n")
            .append("            'egress_ignored_ips': egress_ignored_ips,\n")
            .append("            'ignored_uid': ignored_uid,\n")
            .append("            'proxy_egress_port': proxy_egress_port,\n")
            .append("            'proxy_ingress_port': proxy_ingress_port,\n")
            .append("            'requires_compatibilities': requires_compatibilities,\n")
            .append("            'operating_system_family': operating_system_family,\n")
            .append("            'cpu_architecture': cpu_architecture,\n")
            .append("            'skip_destroy': skip_destroy,\n")
            .append("            'task_role_arn': task_role_arn,\n")
            .append("            'track_latest': track_latest,\n")
            .append("            'volume_name': volume_name,\n")
            .append("            'host_path': host_path,\n")
            .append("            'configure_at_launch': configure_at_launch,\n")
            .append("            'autoprovision': autoprovision,\n")
            .append("            'driver': driver,\n")
            .append("            'scope': scope,\n")
            .append("            'labels': labels,\n")
            .append("            'driver_opts': driver_opts,\n")
            .append("            'efs_file_system_id': efs_file_system_id,\n")
            .append("            'efs_root_directory': efs_root_directory,\n")
            .append("            'transit_encryption': transit_encryption,\n")
            .append("            'transit_encryption_port': transit_encryption_port,\n")
            .append("            'access_point_id': access_point_id,\n")
            .append("            'iam': iam,\n")
            .append("            'fsx_file_system_id': fsx_file_system_id,\n")
            .append("            'fsx_root_directory': fsx_root_directory,\n")
            .append("            'credentials_parameter': credentials_parameter,\n")
            .append("            'domain': domain,\n")
            .append("            'tags': tags\n")
            .append("        }\n")
            .append("        aws_sprout_details['outputs']['aws_sprout']['value'][task_id] = sprout_details\n\n")
            .append("    arn_token = arn_response.get('nextToken')\n")
            .append("    if not arn_token: break\n")

            /** End of Substitution */

            .append("with open(r'" + ROOT_PATH + "/" + authEmailId + "/" + uuid + "/" + region + "/boto3/aws_sprout.json', 'w', encoding='utf-8') as f:\n")
            .append("    json.dump(aws_sprout_details, f, indent=4, default=str, ensure_ascii=False)\n");
        return definedPythonFile.toString();
    }
}
