package click.opentofu.sprout.handler.python.implementations;

import org.springframework.stereotype.Component;

import click.opentofu.sprout.handler.python.interfaces.PythonHandler;

@Component("boto3_instance")
public class AwsInstanceBoto implements PythonHandler {
    @Override
    public String buildAwsPythonFile(String ROOT_PATH, String authEmailId, String uuid, String region, String awsAccessKey, String awsSecretAccessKey, String awsSessionToken) {
        StringBuilder definedPythonFile = new StringBuilder();
        definedPythonFile
            .append("import boto3\n")
            .append("import botocore.exceptions\n")
            .append("from botocore.exceptions import ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError\n")
            .append("import json\n")
            .append("from datetime import datetime\n")
            .append("import base64\n")
            .append("import sys\n")
            .append("from collections import defaultdict\n")
            .append("import logging\n")
            .append("aws_access_key = '" + awsAccessKey + "'\n")
            .append("aws_secret_key = '" + awsSecretAccessKey + "'\n")
            .append("aws_session_token = '" + awsSessionToken + "'\n")
            .append("session = boto3.Session(\n")
            .append("    region_name='" + region + "',\n")
            .append("    aws_access_key_id=aws_access_key,\n")
            .append("    aws_secret_access_key=aws_secret_key,\n")
            .append("    aws_session_token=aws_session_token\n")
            .append(")\n")

            /** Start of Substitution */

            .append("ec2 = session.client('ec2')\n")
            .append("sts = session.client('sts')\n")
            .append("try: \n")
            .append("    caller_identity = sts.get_caller_identity()\n")
            .append("    account_id = caller_identity['Account'] if 'Account' in caller_identity else ''\n")
            .append("except ClientError as e:\n")
            .append("    if e.response['Error']['Code'] == 'ExpiredToken':\n")
            .append("        print('ERROR: AWS temporary credentials expired')\n")
            .append("        sys.exit(1)\n")
            .append("    else:\n")
            .append("        account_id = ''\n")
            .append("except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError): account_id = ''\n")
            .append("aws_instance_details = {'outputs': {'aws_instance': {'value': {}}}}\n")
            .append("instance_token = None\n")
            .append("while True:\n")
            .append("    try: instance_response = ec2.describe_instances(NextToken=instance_token,Filters=[{'Name':'instance-state-name','Values':['running']}]) if instance_token else ec2.describe_instances(Filters=[{'Name':'instance-state-name','Values':['running']}])\n")
            .append("    except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError): instance_response = {}\n")
            .append("    for reservation in instance_response['Reservations'] if 'Reservations' in instance_response else []:\n")
            .append("        for instance in reservation['Instances'] if 'Instances' in reservation else []:\n")
            .append("            if (instance.get('State', {}).get('Name', '')) != 'running': continue\n")
            .append("            instance_arn = ''\n")
            .append("            instance_id = instance.get('InstanceId', '')\n")
            .append("            ami = instance.get('ImageId', '')\n")
            .append("            instance_type = instance.get('InstanceType', '')\n")
            .append("            availability_zone = instance.get('Placement', {}).get('AvailabilityZone', '')\n")
            .append("            subnet_id = instance.get('SubnetId', '')\n")
            .append("            private_ip = instance.get('PrivateIpAddress', '')\n")
            .append("            key_name = instance.get('KeyName', '')\n")
            .append("            iam_instance_profile = instance.get('IamInstanceProfile', {}).get('Arn', '').split('/')[-1]\n")
            .append("            tenancy = instance.get('Placement', {}).get('Tenancy', '')\n")
            .append("            host_id = instance.get('Placement', {}).get('HostId', '')\n")
            .append("            placement_group = instance.get('Placement', {}).get('GroupName', '')\n")
            .append("            placement_group_id = instance.get('Placement', {}).get('GroupId', '')\n")
            .append("            host_resource_group_arn = instance.get('Placement', {}).get('HostResourceGroupArn', '')\n")
            .append("            placement_partition_number = instance.get('Placement', {}).get('PartitionNumber', '')\n")
            .append("            ebs_optimized = instance.get('EbsOptimized', False)\n")
            .append("            hibernation = instance.get('HibernationOptions', {}).get('Configured', False)\n")
            .append("            monitoring = True if instance.get('Monitoring', {}).get('State') == 'enabled' else (False if instance.get('Monitoring', {}).get('State') == 'disabled' else '')\n")
            .append("            source_dest_check = instance.get('SourceDestCheck', False)\n")
            .append("            ipv6_addresses = list(filter(None, (ipv6.get('Ipv6Address') for eni in instance.get('NetworkInterfaces', []) if (eni.get('Attachment', {}).get('DeviceIndex') == 0) for ipv6 in eni.get('Ipv6Addresses', []))))\n")
            .append("            secondary_private_ips = list(filter(None, (item.get('PrivateIpAddress') for eni in instance.get('NetworkInterfaces', []) if (eni.get('Attachment', {}).get('DeviceIndex') == 0) for item in eni.get('PrivateIpAddresses', []) if (item.get('Primary') is False))))\n")
            .append("            vpc_security_group_ids = list(filter(None, (item.get('GroupId') for item in instance.get('SecurityGroups', []))))\n")
            .append("            security_groups = list(filter(None, (item.get('GroupName') for item in instance.get('SecurityGroups', []))))\n")
            .append("            network_interface_id = next((eni.get('NetworkInterfaceId') for eni in instance.get('NetworkInterfaces', []) if (eni.get('Attachment', {}).get('DeviceIndex') == 0)), '')\n")
            .append("            capacity_reservation_preference = instance.get('CapacityReservationSpecification', {}).get('CapacityReservationPreference', '')\n")
            .append("            capacity_reservation_id = instance.get('CapacityReservationId', '')\n")
            .append("            capacity_reservation_resource_group_arn = instance.get('CapacityReservationSpecification', {}).get('CapacityReservationTarget', {}).get('CapacityReservationResourceGroupArn', '')\n")
            .append("            amd_sev_snp = instance.get('CpuOptions', {}).get('AmdSevSnp', '')\n")
            .append("            nested_virtualization = instance.get('CpuOptions', {}).get('NestedVirtualization', '')\n")
            .append("            auto_recovery = instance.get('MaintenanceOptions', {}).get('AutoRecovery', '')\n")
            .append("            http_endpoint = instance.get('MetadataOptions', {}).get('HttpEndpoint', '')\n")
            .append("            http_protocol_ipv6 = instance.get('MetadataOptions', {}).get('HttpProtocolIpv6', '')\n")
            .append("            http_tokens = instance.get('MetadataOptions', {}).get('HttpTokens', '')\n")
            .append("            instance_metadata_tags = instance.get('MetadataOptions', {}).get('InstanceMetadataTags', '')\n")
            .append("            hostname_type = instance.get('PrivateDnsNameOptions', {}).get('HostnameType', '')\n")
            .append("            core_count = instance.get('CpuOptions', {}).get('CoreCount', '')\n")
            .append("            threads_per_core = instance.get('CpuOptions', {}).get('ThreadsPerCore', '')\n")
            .append("            http_put_response_hop_limit = instance.get('MetadataOptions', {}).get('HttpPutResponseHopLimit', '')\n")
            .append("            pri_eni_delete_on_termination = next((eni.get('Attachment', {}).get('DeleteOnTermination') for eni in instance.get('NetworkInterfaces', []) if (eni.get('Attachment', {}).get('DeviceIndex') == 0)), False)\n")
            .append("            enabled = instance.get('EnclaveOptions', {}).get('Enabled', False)\n")
            .append("            enable_resource_name_dns_aaaa_record = instance.get('PrivateDnsNameOptions', {}).get('EnableResourceNameDnsAAAARecord', False)\n")
            .append("            enable_resource_name_dns_a_record = instance.get('PrivateDnsNameOptions', {}).get('EnableResourceNameDnsARecord', False)\n")
            .append("            secondary_subnet_id = [ item.get('SecondarySubnetId', '') for item in instance.get('SecondaryInterfaces', []) ]\n")
            .append("            interface_type = [ item.get('InterfaceType', '') for item in instance.get('SecondaryInterfaces', []) ]\n")
            .append("            network_card_index = [ item.get('Attachment', {}).get('NetworkCardIndex', '') for item in instance.get('SecondaryInterfaces', []) ]\n")
            .append("            device_index = [ item.get('Attachment', {}).get('DeviceIndex', '') for item in instance.get('SecondaryInterfaces', []) ]\n")
            .append("            sec_eni_delete_on_termination = [ item.get('Attachment', {}).get('DeleteOnTermination', False) for item in instance.get('SecondaryInterfaces', []) ]\n")
            .append("            private_ip_addresses = [ list(filter(None, (elem.get('PrivateIpAddress') for elem in item.get('PrivateIpAddresses', [])))) for item in instance.get('SecondaryInterfaces', []) ]\n")
            .append("            try: \n")
            .append("                attr_user_data_response = ec2.describe_instance_attribute(InstanceId=instance_id,Attribute='userData')\n")
            .append("                user_data = base64.b64decode(attr_user_data_response['UserData']['Value'] if 'UserData' in attr_user_data_response and 'Value' in attr_user_data_response['UserData'] else '').decode('utf-8')\n")
            .append("            except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError,base64.binascii.Error,UnicodeDecodeError): user_data = ''\n")
            .append("            try: \n")
            .append("                attr_disable_api_stop_response = ec2.describe_instance_attribute(InstanceId=instance_id,Attribute='disableApiStop')\n")
            .append("                disable_api_stop = attr_disable_api_stop_response.get('DisableApiStop', {}).get('Value', False) \n")
            .append("            except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError,base64.binascii.Error,UnicodeDecodeError): disable_api_stop = False\n")
            .append("            try: \n")
            .append("                attr_disable_api_termination_response = ec2.describe_instance_attribute(InstanceId=instance_id,Attribute='disableApiTermination')\n")
            .append("                disable_api_termination = attr_disable_api_termination_response.get('DisableApiTermination', {}).get('Value', False) \n")
            .append("            except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError,base64.binascii.Error,UnicodeDecodeError): disable_api_termination = False\n")
            .append("            try: \n")
            .append("                credit_spec_response = ec2.describe_instance_credit_specifications(InstanceIds=[instance_id])\n")
            .append("                cpu_credits = next((item.get('CpuCredits') for item in credit_spec_response.get('InstanceCreditSpecifications', [])), '')\n")
            .append("            except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError,base64.binascii.Error,UnicodeDecodeError): cpu_credits = ''\n")
            .append("            volumes_response = {'Volumes': []}\n")
            .append("            try: \n")
            .append("                volumes_response = ec2.describe_volumes(Filters=[{'Name':'attachment.instance-id','Values':[instance_id]},{'Name':'attachment.status','Values':['attached']}])\n")
            .append("            except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError,base64.binascii.Error,UnicodeDecodeError): pass\n")
            .append("            root_dev_delete_on_termination = next((attach.get('DeleteOnTermination') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') == instance.get('RootDeviceName'))), False)\n")
            .append("            root_dev_encrypted = next((item.get('Encrypted') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') == instance.get('RootDeviceName'))), False)\n")
            .append("            root_dev_iops = next((item.get('Iops') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') == instance.get('RootDeviceName'))), '')\n")
            .append("            root_dev_kms_key_id = next((item.get('KmsKeyId') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') == instance.get('RootDeviceName'))), '')\n")
            .append("            root_dev_throughput = next((item.get('Throughput') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') == instance.get('RootDeviceName'))), '')\n")
            .append("            root_dev_volume_size = next((item.get('Size') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') == instance.get('RootDeviceName'))), '')\n")
            .append("            root_dev_volume_type = next((item.get('VolumeType') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') == instance.get('RootDeviceName'))), '')\n")
            .append("            root_dev_tags = next((dict(filter(lambda pair: pair[0] is not None, ((tag.get('Key'), tag.get('Value', '')) for tag in item.get('Tags', [])))) for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') == instance.get('RootDeviceName'))), {})\n")
            .append("            ebs_dev_delete_on_termination = [ attach.get('DeleteOnTermination', False) for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_device_name = [ attach.get('Device', '') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_encrypted = [ item.get('Encrypted', False) for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_iops = [ item.get('Iops', '') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_kms_key_id = [ item.get('KmsKeyId', '') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_snapshot_id = [ item.get('SnapshotId', '') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_throughput = [ item.get('Throughput', '') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_volume_size = [ item.get('Size', '') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_volume_type = [ item.get('VolumeType', '') for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            ebs_dev_tags = [ dict(filter(lambda pair: pair[0] is not None, ((tag.get('Key'), tag.get('Value', '')) for tag in item.get('Tags', [])))) for item in volumes_response.get('Volumes', []) for attach in item.get('Attachments', []) if (attach.get('InstanceId') == instance_id and attach.get('Device') != instance.get('RootDeviceName')) ]\n")
            .append("            tags = { tag['Key']: tag['Value'] for tag in (instance['Tags'] if 'Tags' in instance else []) if 'Key' in tag and 'Value' in tag }\n")
            .append("            ipv6_address_count = ''\n")
            .append("            associate_public_ip_address = ''\n")
            .append("            force_destroy = ''\n")
            .append("            get_password_data = ''\n")
            .append("            user_data_replace_on_change = ''\n")
            .append("            enable_primary_ipv6 = ''\n")
            .append("            market_type = ''\n")
            .append("            instance_interruption_behavior = ''\n")
            .append("            max_price = ''\n")
            .append("            spot_instance_type = ''\n")
            .append("            valid_until = ''\n")
            .append("            lt_id = ''\n")
            .append("            lt_name = ''\n")
            .append("            lt_version = ''\n")
            .append("            eph_dev_device_name = []\n")
            .append("            virtual_name = []\n")
            .append("            private_ip_address_count = []\n")
            .append("            no_device = []\n")
            .append("            volume_tags = {}\n")
            .append("            instance_details = {\n")
            .append("                'account_id': account_id,\n")
            .append("                'region': '" + region + "',\n")
            .append("                'instance_arn': instance_arn,\n")
            .append("                'instance_id': instance_id,\n")
            .append("                'ami': ami,\n")
            .append("                'instance_type': instance_type,\n")
            .append("                'availability_zone': availability_zone,\n")
            .append("                'subnet_id': subnet_id,\n")
            .append("                'private_ip': private_ip,\n")
            .append("                'key_name': key_name,\n")
            .append("                'iam_instance_profile': iam_instance_profile,\n")
            .append("                'tenancy': tenancy,\n")
            .append("                'host_id': host_id,\n")
            .append("                'placement_group': placement_group,\n")
            .append("                'placement_group_id': placement_group_id,\n")
            .append("                'host_resource_group_arn': host_resource_group_arn,\n")
            .append("                'ipv6_address_count': ipv6_address_count,\n")
            .append("                'placement_partition_number': placement_partition_number,\n")
            .append("                'associate_public_ip_address': associate_public_ip_address,\n")
            .append("                'disable_api_stop': disable_api_stop,\n")
            .append("                'disable_api_termination': disable_api_termination,\n")
            .append("                'ebs_optimized': ebs_optimized,\n")
            .append("                'force_destroy': force_destroy,\n")
            .append("                'get_password_data': get_password_data,\n")
            .append("                'hibernation': hibernation,\n")
            .append("                'monitoring': monitoring,\n")
            .append("                'source_dest_check': source_dest_check,\n")
            .append("                'user_data_replace_on_change': user_data_replace_on_change,\n")
            .append("                'enable_primary_ipv6': enable_primary_ipv6,\n")
            .append("                'ipv6_addresses': ipv6_addresses,\n")
            .append("                'secondary_private_ips': secondary_private_ips,\n")
            .append("                'vpc_security_group_ids': vpc_security_group_ids,\n")
            .append("                'security_groups': security_groups,\n")
            .append("                'user_data': user_data,\n")
            .append("                'market_type': market_type,\n")
            .append("                'instance_interruption_behavior': instance_interruption_behavior,\n")
            .append("                'max_price': max_price,\n")
            .append("                'spot_instance_type': spot_instance_type,\n")
            .append("                'valid_until': valid_until,\n")
            .append("                'lt_id': lt_id,\n")
            .append("                'lt_name': lt_name,\n")
            .append("                'lt_version': lt_version,\n")
            .append("                'network_interface_id': network_interface_id,\n")
            .append("                'pri_eni_delete_on_termination': pri_eni_delete_on_termination,\n")
            .append("                'capacity_reservation_preference': capacity_reservation_preference,\n")
            .append("                'capacity_reservation_id': capacity_reservation_id,\n")
            .append("                'capacity_reservation_resource_group_arn': capacity_reservation_resource_group_arn,\n")
            .append("                'amd_sev_snp': amd_sev_snp,\n")
            .append("                'core_count': core_count,\n")
            .append("                'nested_virtualization': nested_virtualization,\n")
            .append("                'threads_per_core': threads_per_core,\n")
            .append("                'cpu_credits': cpu_credits,\n")
            .append("                'enabled': enabled,\n")
            .append("                'auto_recovery': auto_recovery,\n")
            .append("                'http_endpoint': http_endpoint,\n")
            .append("                'http_protocol_ipv6': http_protocol_ipv6,\n")
            .append("                'http_put_response_hop_limit': http_put_response_hop_limit,\n")
            .append("                'http_tokens': http_tokens,\n")
            .append("                'instance_metadata_tags': instance_metadata_tags,\n")
            .append("                'enable_resource_name_dns_aaaa_record': enable_resource_name_dns_aaaa_record,\n")
            .append("                'enable_resource_name_dns_a_record': enable_resource_name_dns_a_record,\n")
            .append("                'hostname_type': hostname_type,\n")
            .append("                'root_dev_delete_on_termination': root_dev_delete_on_termination,\n")
            .append("                'root_dev_encrypted': root_dev_encrypted,\n")
            .append("                'root_dev_iops': root_dev_iops,\n")
            .append("                'root_dev_kms_key_id': root_dev_kms_key_id,\n")
            .append("                'root_dev_throughput': root_dev_throughput,\n")
            .append("                'root_dev_volume_size': root_dev_volume_size,\n")
            .append("                'root_dev_volume_type': root_dev_volume_type,\n")
            .append("                'root_dev_tags': root_dev_tags,\n")
            .append("                'ebs_dev_delete_on_termination': ebs_dev_delete_on_termination,\n")
            .append("                'ebs_dev_device_name': ebs_dev_device_name,\n")
            .append("                'ebs_dev_encrypted': ebs_dev_encrypted,\n")
            .append("                'ebs_dev_iops': ebs_dev_iops,\n")
            .append("                'ebs_dev_kms_key_id': ebs_dev_kms_key_id,\n")
            .append("                'ebs_dev_snapshot_id': ebs_dev_snapshot_id,\n")
            .append("                'ebs_dev_throughput': ebs_dev_throughput,\n")
            .append("                'ebs_dev_volume_size': ebs_dev_volume_size,\n")
            .append("                'ebs_dev_volume_type': ebs_dev_volume_type,\n")
            .append("                'ebs_dev_tags': ebs_dev_tags,\n")
            .append("                'eph_dev_device_name': eph_dev_device_name,\n")
            .append("                'virtual_name': virtual_name,\n")
            .append("                'no_device': no_device,\n")
            .append("                'secondary_subnet_id': secondary_subnet_id,\n")
            .append("                'network_card_index': network_card_index,\n")
            .append("                'device_index': device_index,\n")
            .append("                'interface_type': interface_type,\n")
            .append("                'sec_eni_delete_on_termination': sec_eni_delete_on_termination,\n")
            .append("                'private_ip_address_count': private_ip_address_count,\n")
            .append("                'private_ip_addresses': private_ip_addresses,\n")
            .append("                'volume_tags': volume_tags,\n")
            .append("                'tags': tags\n")
            .append("            }\n")
            .append("            aws_instance_details['outputs']['aws_instance']['value'][instance_id] = instance_details\n")
            .append("    instance_token = instance_response.get('NextToken')\n")
            .append("    if not instance_token: break\n")

            /** End of Substitution */

            .append("with open(r'" + ROOT_PATH + "/" + authEmailId + "/" + uuid + "/" + region + "/boto3/aws_instance.json', 'w', encoding='utf-8') as f:\n")
            .append("    json.dump(aws_instance_details, f, indent=4, default=str, ensure_ascii=False)\n");
        return definedPythonFile.toString();
    }
}
