package click.opentofu.sprout.handler.python.implementations;

import org.springframework.stereotype.Component;

import click.opentofu.sprout.handler.python.interfaces.PythonHandler;

@Component("boto3_security_group")
public class AwsSecurityGroupBoto implements PythonHandler {
    @Override
    public String buildAwsPythonFile(String ROOT_PATH, String authEmailId, String uuid, String region, String awsAccessKey, String awsSecretAccessKey, String awsSessionToken) {
        StringBuilder definedPythonFile = new StringBuilder();
        definedPythonFile
            .append("import boto3\n")
            .append("import botocore.exceptions\n")
            .append("from botocore.exceptions import ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError\n")
            .append("import json\n")
            .append("from datetime import datetime\n")
            .append("import base64\n")
            .append("import sys\n")
            .append("from collections import defaultdict\n")
            .append("import logging\n")
            .append("aws_access_key = '" + awsAccessKey + "'\n")
            .append("aws_secret_key = '" + awsSecretAccessKey + "'\n")
            .append("aws_session_token = '" + awsSessionToken + "'\n")
            .append("session = boto3.Session(\n")
            .append("    region_name='" + region + "',\n")
            .append("    aws_access_key_id=aws_access_key,\n")
            .append("    aws_secret_access_key=aws_secret_key,\n")
            .append("    aws_session_token=aws_session_token\n")
            .append(")\n")

            /** Start of Substitution */

            .append("ec2 = session.client('ec2')\n")
            .append("sts = session.client('sts')\n")
            .append("try: \n")
            .append("    caller_identity = sts.get_caller_identity()\n")
            .append("    account_id = caller_identity['Account'] if 'Account' in caller_identity else ''\n")
            .append("except ClientError as e:\n")
            .append("    if e.response['Error']['Code'] == 'ExpiredToken':\n")
            .append("        print('ERROR: AWS temporary credentials expired')\n")
            .append("        sys.exit(1)\n")
            .append("    else:\n")
            .append("        account_id = ''\n")
            .append("except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError): account_id = ''\n")
            .append("aws_security_group_details = {'outputs': {'aws_security_group': {'value': {}}}}\n")
            .append("security_group_token = None\n")
            .append("while True:\n")
            .append("    try: security_group_response = ec2.describe_security_groups(NextToken=security_group_token) if security_group_token else ec2.describe_security_groups()\n")
            .append("    except (ClientError,ParamValidationError,EndpointConnectionError,NoCredentialsError): security_group_response = {}\n")
            .append("    for security_group in security_group_response['SecurityGroups'] if 'SecurityGroups' in security_group_response else []:\n")
            .append("        security_group_arn = security_group.get('SecurityGroupArn', '')\n")
            .append("        security_group_id = security_group.get('GroupId', '')\n")
            .append("        description = security_group.get('Description', '')\n")
            .append("        security_group_name = security_group.get('GroupName', '')\n")
            .append("        name_prefix = ''\n")
            .append("        vpc_id = security_group.get('VpcId', '')\n")
            .append("        revoke_rules_on_delete = False\n")
            .append("        ingress_self = []\n")
            .append("        egress_self = []\n")
            .append("        rules = defaultdict(list)\n")
            .append("        directions = [\n")
            .append("            ('ingress', security_group.get('IpPermissions', [])),\n")
            .append("            ('egress',  security_group.get('IpPermissionsEgress', [])),\n")
            .append("        ]\n")
            .append("        for direction, permissions in directions:\n")
            .append("            for perm in permissions:\n")
            .append("                protocol = perm.get('IpProtocol', '')\n")
            .append("                from_port = perm.get('FromPort') if protocol != '-1' else '0'\n")
            .append("                to_port = perm.get('ToPort') if protocol != '-1' else '0'\n")
            .append("                for item in perm.get('UserIdGroupPairs', []):\n")
            .append("                    key = (direction, protocol, from_port, to_port, 'security_groups', item.get('Description', ''))\n")
            .append("                    rules[key].append(item.get('GroupId', ''))\n")
            .append("                for item in perm.get('IpRanges', []):\n")
            .append("                    key = (direction, protocol, from_port, to_port, 'cidr_blocks', item.get('Description', ''))\n")
            .append("                    rules[key].append(item.get('CidrIp', ''))\n")
            .append("                for item in perm.get('Ipv6Ranges', []):\n")
            .append("                    key = (direction, protocol, from_port, to_port, 'ipv6_cidr_blocks', item.get('Description', ''))\n")
            .append("                    rules[key].append(item.get('CidrIpv6', ''))\n")
            .append("                for item in perm.get('PrefixListIds', []):\n")
            .append("                    key = (direction, protocol, from_port, to_port, 'prefix_list_ids', item.get('Description', ''))\n")
            .append("                    rules[key].append(item.get('PrefixListId', ''))\n")
            .append("        ingress_protocol = []\n")
            .append("        ingress_from_port = []\n")
            .append("        ingress_to_port = []\n")
            .append("        ingress_description = []\n")
            .append("        ingress_cidr_blocks = []\n")
            .append("        ingress_ipv6_cidr_blocks = []\n")
            .append("        ingress_prefix_list_ids = []\n")
            .append("        ingress_security_groups = []\n")
            .append("        egress_protocol = []\n")
            .append("        egress_from_port = []\n")
            .append("        egress_to_port = []\n")
            .append("        egress_description = []\n")
            .append("        egress_cidr_blocks = []\n")
            .append("        egress_ipv6_cidr_blocks = []\n")
            .append("        egress_prefix_list_ids = []\n")
            .append("        egress_security_groups = []\n")
            .append("        for (direction, protocol, from_port, to_port, source_type, desc), sources in rules.items():\n")
            .append("            if direction == 'ingress':\n")
            .append("                ingress_protocol.append(protocol)\n")
            .append("                ingress_from_port.append(from_port)\n")
            .append("                ingress_to_port.append(to_port)\n")
            .append("                ingress_description.append(desc)\n")
            .append("                ingress_cidr_blocks.append(sources if source_type == 'cidr_blocks' else []) \n")
            .append("                ingress_ipv6_cidr_blocks.append(sources if source_type == 'ipv6_cidr_blocks' else [])\n")
            .append("                ingress_prefix_list_ids.append(sources if source_type == 'prefix_list_ids' else [])\n")
            .append("                ingress_security_groups.append(sources if source_type == 'security_groups' else [])\n")
            .append("            else:\n")
            .append("                egress_protocol.append(protocol)\n")
            .append("                egress_from_port.append(from_port)\n")
            .append("                egress_to_port.append(to_port)\n")
            .append("                egress_description.append(desc)\n")
            .append("                egress_cidr_blocks.append(sources if source_type == 'cidr_blocks' else [])\n")
            .append("                egress_ipv6_cidr_blocks.append(sources if source_type == 'ipv6_cidr_blocks' else [])\n")
            .append("                egress_prefix_list_ids.append(sources if source_type == 'prefix_list_ids' else [])\n")
            .append("                egress_security_groups.append(sources if source_type == 'security_groups' else [])\n")
            .append("        tags = { tag['Key']: tag['Value'] for tag in (security_group['Tags'] if 'Tags' in security_group else []) if 'Key' in tag and 'Value' in tag }\n")
            .append("        security_group_details = {\n")
            .append("            'account_id': account_id,\n")
            .append("            'region': '" + region + "',\n")
            .append("            'security_group_arn': security_group_arn,\n")
            .append("            'security_group_id': security_group_id,\n")
            .append("            'description': description,\n")
            .append("            'security_group_name': security_group_name,\n")
            .append("            'name_prefix': name_prefix,\n")
            .append("            'vpc_id': vpc_id,\n")
            .append("            'revoke_rules_on_delete': revoke_rules_on_delete,\n")
            .append("            'ingress_protocol': ingress_protocol,\n")
            .append("            'ingress_description': ingress_description,\n")
            .append("            'egress_protocol': egress_protocol,\n")
            .append("            'egress_description': egress_description,\n")
            .append("            'ingress_from_port': ingress_from_port,\n")
            .append("            'ingress_to_port': ingress_to_port,\n")
            .append("            'egress_from_port': egress_from_port,\n")
            .append("            'egress_to_port': egress_to_port,\n")
            .append("            'ingress_self': ingress_self,\n")
            .append("            'egress_self': egress_self,\n")
            .append("            'ingress_cidr_blocks': ingress_cidr_blocks,\n")
            .append("            'ingress_ipv6_cidr_blocks': ingress_ipv6_cidr_blocks,\n")
            .append("            'ingress_prefix_list_ids': ingress_prefix_list_ids,\n")
            .append("            'ingress_security_groups': ingress_security_groups,\n")
            .append("            'egress_cidr_blocks': egress_cidr_blocks,\n")
            .append("            'egress_ipv6_cidr_blocks': egress_ipv6_cidr_blocks,\n")
            .append("            'egress_prefix_list_ids': egress_prefix_list_ids,\n")
            .append("            'egress_security_groups': egress_security_groups,\n")
            .append("            'tags': tags\n")
            .append("        }\n")
            .append("        aws_security_group_details['outputs']['aws_security_group']['value'][security_group_id] = security_group_details\n")
            .append("    security_group_token = security_group_response.get('NextToken')\n")
            .append("    if not security_group_token: break\n")

            /** End of Substitution */

            .append("with open(r'" + ROOT_PATH + "/" + authEmailId + "/" + uuid + "/" + region + "/boto3/aws_security_group.json', 'w', encoding='utf-8') as f:\n")
            .append("    json.dump(aws_security_group_details, f, indent=4, default=str, ensure_ascii=False)\n");
        return definedPythonFile.toString();
    }
}
